sonar.projectKey=SW2_week4
sonar.projectName=SW2_week4
sonar.projectVersion=1.0


sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes
sonar.java.coveragePlugin=jacoco
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml


sonar.host.url=http://localhost:9000
sonar.login=squ_498655a7e613781c23b9bca9d9775a6ec0697180